In [8]:
import pandas as pd
from pandas import DataFrame

df_103N = pd.read_csv('人口密度/opendata103N010.csv')
#df_103N.info()
df_103N

    statistic_yyy  ... population_density
0             統計年  ...               人口密度
1             103  ...              24027
2             103  ...              23860
3             103  ...              20613
4             103  ...              39775
..            ...  ...                ...
370           103  ...                  …
371           NaN  ...                NaN
372           NaN  ...                NaN
373           NaN  ...                NaN
374           NaN  ...                NaN

[375 rows x 5 columns]