In [34]:
import numpy as np
import pandas as pd

scores = pd.DataFrame(np.random.randint(50,101,size=(50,5)),
             columns=['國文', '英文', '數學', '地理', '歷史'],
             index=range(1,51))

scores

    國文  英文  數學   地理  歷史
1   59  77  82   92  65
2   93  57  60   67  95
3   75  73  82  100  66
4   97  79  57   96  95
5   66  81  56   74  76
6   62  84  96   93  92
7   93  96  95   54  67
8   78  72  83   94  82
9   78  76  72   53  57
10  82  65  72   71  57
11  96  50  76  100  91
12  82  89  57   88  91
13  84  81  82   83  72
14  79  62  57   68  81
15  72  51  86   98  83
16  94  67  71   54  80
17  86  95  61   88  53
18  75  81  83   77  68
19  79  60  61   87  91
20  81  83  52   96  66
21  60  64  58   95  65
22  64  72  98   90  77
23  69  56  61   55  65
24  61  54  98   87  91
25  90  90  86   85  61
26  55  53  83   93  76
27  94  91  85   61  97
28  97  94  72   53  85
29  72  50  65   67  81
30  63  55  70   78  58
31  99  82  61   94  89
32  80  69  91   64  83
33  70  69  90   80  92
34  56  85  99   94  75
35  98  83  91   91  71
36  55  88  94   68  52
37  96  91  82   58  88
38  56  77  50   85  98
39  58  82  66   78  81
40  50  71  90   86  93
41  73  70  69   60  93
42  99  90  89   54  65
43  65  57  69   66  67
44  64  72  92   57  61
45  63  63  75   82  95
46  78  50  96   82  82
47  60  84  90   88  79
48  94  56  93   71  64
49  57  80  74   73  67
50  97  61  85   73  54

In [35]:
def abc(s):
    return s.max()
scores.apply(abc)

國文     99
英文     96
數學     99
地理    100
歷史     98
dtype: int64

In [36]:
def abc(s):
    return pd.Series([s.min(),s.max(),s.mean()], index=['最低分','最高分','平均'])
scores.apply(abc)

        國文     英文     數學      地理     歷史
最低分  50.00  50.00  50.00   53.00  52.00
最高分  99.00  96.00  99.00  100.00  98.00
平均   76.08  72.76  77.26   78.02  76.66

In [37]:
scores.index = scores.index.map(lambda i:f'{i}號')
scores

     國文  英文  數學   地理  歷史
1號   59  77  82   92  65
2號   93  57  60   67  95
3號   75  73  82  100  66
4號   97  79  57   96  95
5號   66  81  56   74  76
6號   62  84  96   93  92
7號   93  96  95   54  67
8號   78  72  83   94  82
9號   78  76  72   53  57
10號  82  65  72   71  57
11號  96  50  76  100  91
12號  82  89  57   88  91
13號  84  81  82   83  72
14號  79  62  57   68  81
15號  72  51  86   98  83
16號  94  67  71   54  80
17號  86  95  61   88  53
18號  75  81  83   77  68
19號  79  60  61   87  91
20號  81  83  52   96  66
21號  60  64  58   95  65
22號  64  72  98   90  77
23號  69  56  61   55  65
24號  61  54  98   87  91
25號  90  90  86   85  61
26號  55  53  83   93  76
27號  94  91  85   61  97
28號  97  94  72   53  85
29號  72  50  65   67  81
30號  63  55  70   78  58
31號  99  82  61   94  89
32號  80  69  91   64  83
33號  70  69  90   80  92
34號  56  85  99   94  75
35號  98  83  91   91  71
36號  55  88  94   68  52
37號  96  91  82   58  88
38號  56  77  50   85  98
39號  58  82  66   78  81
40號  50  71  90   86  93
41號  73  70  69   60  93
42號  99  90  89   54  65
43號  65  57  69   66  67
44號  64  72  92   57  61
45號  63  63  75   82  95
46號  78  50  96   82  82
47號  60  84  90   88  79
48號  94  56  93   71  64
49號  57  80  74   73  67
50號  97  61  85   73  54

In [41]:
def abc1(item):
    less_student = item[item < 60]
    less_count = less_student.count()
    less_str = ",".join(less_student.index.values.tolist())
    
    return pd.Series([item.sum(), item.mean()],index=['總分', '平均'])
scores.apply(abc1, axis=1)

        總分    平均
1號   375.0  75.0
2號   372.0  74.4
3號   396.0  79.2
4號   424.0  84.8
5號   353.0  70.6
6號   427.0  85.4
7號   405.0  81.0
8號   409.0  81.8
9號   336.0  67.2
10號  347.0  69.4
11號  413.0  82.6
12號  407.0  81.4
13號  402.0  80.4
14號  347.0  69.4
15號  390.0  78.0
16號  366.0  73.2
17號  383.0  76.6
18號  384.0  76.8
19號  378.0  75.6
20號  378.0  75.6
21號  342.0  68.4
22號  401.0  80.2
23號  306.0  61.2
24號  391.0  78.2
25號  412.0  82.4
26號  360.0  72.0
27號  428.0  85.6
28號  401.0  80.2
29號  335.0  67.0
30號  324.0  64.8
31號  425.0  85.0
32號  387.0  77.4
33號  401.0  80.2
34號  409.0  81.8
35號  434.0  86.8
36號  357.0  71.4
37號  415.0  83.0
38號  366.0  73.2
39號  365.0  73.0
40號  390.0  78.0
41號  365.0  73.0
42號  397.0  79.4
43號  324.0  64.8
44號  346.0  69.2
45號  378.0  75.6
46號  388.0  77.6
47號  401.0  80.2
48號  378.0  75.6
49號  351.0  70.2
50號  370.0  74.0

In [39]:
one_student = scores.iloc[0]
less_student = one_student[one_student < 60]
less_student

國文    59
Name: 1號, dtype: int64

In [40]:
less_student.count()
",".join(less_student.index.values.tolist())

'國文'